<?php include_once("header.php") ?>
<style>
p{
	text-align:justify;
}
</style>

<!-- ####################################################################################################### -->
<div class="wrapper row4">
  <div id="container" class="clear"> 
    <!-- ####################################################################################################### -->
    <div id="content">
      <h1 style="color:#000;">History</h1>
      <img class="imgr" src="images/images/open_hand_chandigarh.jpg"
       width="125" height="125" />
      <p>Located on the north of India, 365 meters above the sea-level, on the foot-hills of Shivalik range, is the city beautiful,'Chandigarh'. It is the capital of two States of the Indian Union, namely, the Punjab and Haryana.Though it is the capital of two states, it belongs to none of them and is a Union Territory Before the partition of India, on August 15, 1947, the areas which are now parts of the Punjab, Haryana, Delhi, some parts of Himachal Pradesh and some areas falling in West Pakistan, formed the Punjab. Lahore was its capital.</p>
      <p style="text-align:justify;">In the partition, Lahore was given to Pakistan. There arose the need to have a new capital for the areas of the Punjab that had fallen to India.In March, 1948, the Government of Punjab in consultation with the Government of India, approved a 114.59 sq.km. tract of land at the foot of the Shivalik Hills in Ambala district, as the site for the new capital. Le Corbusier, a well-known, French architect, was chosen to execute the project. India's first Prime Minister, Jawaharlal Nehru, enthusiastically supported the project and took sustained interest in its execution. When he visited the project on April 2, 1952, he declared Let this be a new town symbolic of the freedom of India, unfettered by the traditions of the past, an expression of the nation's faith in the future....The new capital of Punjab will be christened as Chandigarh - a name symbolic of the valiant spirit of the Punjabis. Chandigarh is rightly associated with the name of Goddess Chandi -Shakti, or power. Situated at a distance of about 240 kilometers on the north of Delhi on National Highway No.21, it is connected by bus, rail and air. Chandigarh is known all over the world for its being the first planned Asian city. The City is divided into well-planned and defined sectors. Each sector is a separate self-reliant unit, having all the essential amenities, such as, school,dispensary, post office, market etc. The City also boasts of open parks and wide roads. Being the capital of the two states, the administrative headquarters of both the States are also located here. Many people from other parts of India and the world visit it every day to see the architecture of its buildings. Zakir Rose Garden, Rock Garden and Sukhna Lake are some of the places of interest in the city. It is also the seat of the High Court of the Punjab and Haryana. The High Court is located in Sector 1 of Chandigarh.</p>
      <img class="imgl" src="images/images/highcourt_lahore.jpg" alt="" width="125" height="125" />
      <p>After the partition of India, the Constitution of India was framed. However, before the partition, there was the Government of India Act, 1915. By virtue of the powers conferred by Section 113 of the Government of India Act,1915, the Crown by Letters Patent dated March 20, 1919 had established at Lahore, the High Court of judicature for the provinces of Punjab and Delhi to be called 'the High Court of judicature at Lahore'. The High Court of judicature at Lahore was a court of record.</p>
      <p>On the establishment of the Lahore High Court, the Chief Court of Punjab, which was functioning for the last 53 years, was abolished. The High Court at Lahore by virtue of Letters Patent and Section 106 and 113 of the Government of India Act, 1915 was vested with all the appellate and superintending powers, authority and jurisdiction of the Chief Court. The Lahore High Court by its Letters Patent was also vested with original jurisdiction in certain special matters as were possessed by the Chief Court. These special matters included disciplinary action against Advocates (Clause 8); Guardianship (Clause 12); testamentary and intestate (Clause 24)and matrimonial matters (Clause 22). The High Court had no ordinary original civil jurisdiction. However, it had ordinary original criminal jurisdiction to a limited extent. The original criminal jurisdiction of the Lahore High court was co-extensive with that of the chief court of Punjab which had no original criminal jurisdiction to try any person, except European British subjects. As per Clause 9 of the Letters Patent, it was empowered to remove, try and determine any civil case from courts subordinate to it. In exercise of its appellate jurisdiction, the Lahore High Court was authorized to hear appeals from the decisions of all the criminal and other courts of the provinces of Punjab, Delhi and all other Courts subject to its superintendence. It could hear appeals in Benches of two or more Judges of its own Court sitting on the civil side. </p>
      <p>It was also declared to be Court of reference and revision from the criminal courts subject to its appellate jurisdiction. It had the powerto transfer any criminal case or appeal from any court to any other court of equal or superior jurisdiction. It had no power to issue writs except to the extent as it was empowered to issue orders in the nature of habeas corpus under Section 491 of the Code of Criminal Procedure along with other High Courts. </p>
      <h2>Post Independence scenario</h2>
     	<p>After independence of India, the old province of Punjab was divided into West Punjab (Pakistan) and East Punjab (India). The High Court at Lahore being in Pakistan, ceased to have jurisdiction over Delhi and East Punjab. The question of location of the new High Court for these provinces arose. Shimla was selected as the seat of the new High Court.</p>
     <img src="images/images/peterhoff_simla_highcourt.jpg" width="100%" />   
      his is an example of a comment made on a post. You can either edit the comment, delete the comment or reply to the comment. Use this as a place to respond to the post or to share what you are thinking.</p>
      <p>The East Punjab High Court of judicature was established at Shimla on August 15, 1947 by the Governor General's High Court (Punjab) Order 1947 issued under Section 9 of the Indian Independence Act, 1947. In exercise of the powers conferred by Section 229 (1) of the Government of India Act, 1935, the High Court of East Punjab was also made a court of record and as provided by Clause 5 of the said order, it had in respect of the provinces of Punjab and Delhi, all such original, appellate and other jurisdictions as under the law in force immediately before the August 15, 1947, was exercisable in respect of those territories by the High Court at Lahore. The East Punjab High Court was the successor and continuation of the High Court at Lahore. The decisions of Lahore High Court were binding on the Punjab High Court on the principle of stare decisis. The Constitution of India came into force on January 26, 1950. The State of East Punjab came to be known as the Punjab now. Accordingly, the name of the High Court was also changed. As per Article 214(2) of the Constitution of India, the High Court was to be continued along with other High Courts. The Constitution of India also conferred on the Punjab High Court, along with all other High Courts, the power to issue directions, orders including writs in the nature of habeas corpus, mandamus, prohibition, quo-warranto and certiorari in the enforcement of fundamental rights or for any other purpose. The East Punjab High Court did not have the power to issue writs. However, the seat of the High Court continued to remain at Shimla.</p>
      <h2>High Court shifted..</h2>
<p>On account of its inclement weather in winter, 
it was very inconvenient for the litigants to go to Shimla. Accordingly, 
the seat of the High Court was shifted to Chandigarh.<b> The Court started functioning at Chandigarh from its present building with effect from January 17, 1955.</b>
</p>
<img src="images/images/nehruji_speach.jpg" width="100%" />
    </div>
    <?php include_once("sidebar.php") ?>
    <!-- ####################################################################################################### -->
    <div class="clear"></div>
  </div>
</div>
<!-- ####################################################################################################### -->
<?php include_once("footer.php") ?>